### ISSUE TITLE
mine keeps booting into fastboot

### ISSUE THREAD

**Issue by benwywywywy** [untocodes/lenovo-cube-hacking#7]
i reflashed the firmware and it keeps booting into fastboot

**Comment by benwywywywy** [comment]
and also how do i boot it into the stock android things

**Comment by Jens-Wymeersch** [comment]
@benwywywywy I'm following https://forum.xda-developers.com/t/lenovo-smart-clock-bootloader-avb-unlock-firmware-region-changer-kernel-source.4130295/ 
I wonder if you can explain what you did ?

**Comment by untocodes** [comment]
I'd suggest discussing this firmware and it's details in the XDA thread linked above.
