### ISSUE TITLE
How did you get ADB working?

### ISSUE THREAD

**Issue by lyonzy** [untocodes/lenovo-cube-hacking#9]
Hey, 

Thanks for this info! I've gotten to the point of getting the loading spinner because it can't get to its TEE. 

You mentioned ADB works - how did you manage that? Was that on the debug builds that's only on slot A of new devices? I'm happy that I can flash ROMs (and I also have been able to mount the img files and fiddle a bit) but no matter what I do I can't get past the spinner, and I'm wondering if ADB only gets enabled at some point in the boot process after the point at which it gets stuck.

**Comment by lyonzy** [comment]
All good, figured it out - you need the custom USB cable with these connections:

![image](https://user-images.githubusercontent.com/11625419/234188671-58adc6e5-6885-486c-a337-087b1342b2ac.png)

Thanks to this video (it's in French but I managed to get the key points despite not speaking French):
https://www.youtube.com/watch?v=kTw5xtEWnBY

**Comment by ingoau** [comment]
Just wondering, how exactly did you do this? Did you use one usb 3 and one usb 2 cable? Or does it not matter?

**Comment by ingoau** [comment]
I think I get this now
